#!/bin/sh
KERNEL="/boot/$(basename "$(readlink -f /vmlinuz)")"
INITRD="/boot/$(basename "$(readlink -f /initrd.img)")"
cat <<MENU
menuentry 'Normal boot' --id konotop-normal {
  search --set=root --label root
  linux $KERNEL root=LABEL=root ro quiet
  initrd $INITRD
}
menuentry 'Restore system (data is preserved)' --id konotop-recover {
  search --set=root --label root
  linux $KERNEL root=LABEL=root ro konotop.recover=1 ROOT_PART=/dev/disk/by-label/root REC_PART=/dev/disk/by-label/recovery
  initrd /boot/konotop-recovery.img
}
menuentry 'Create golden snapshot (admin)' --id konotop-rebless {
  search --set=root --label root
  linux $KERNEL root=LABEL=root ro konotop.rebless=1 ROOT_PART=/dev/disk/by-label/root REC_PART=/dev/disk/by-label/recovery
  initrd /boot/konotop-recovery.img
}
MENU
